### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ajbraus** [ryanlsmith4/weather_api#1]
Reviewing your take home project!
1. Very good modularity
2. Great simple testing (this really signals that you are a professional)
3. Interesting use of node-localstorage, never seen this before
4. I think you’d definitely get into the next round with this project
5. I wish there was a way to put your weatherapi key into the project so it was easier to just clone and run, maybe if you hard-coded it instead of putting in .env

**Comment by ryanlsmith4** [comment]
Thanks Great Feedback!
